name: Docker build/publish when base image is updated
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      needs-updating: ${{ steps.check.outputs.needs-updating }}
    steps:
      - name: Check if update available
        id: check
        
        uses: ClementTsang/docker-check-base-image-diff@v0.0.2
        with:
          base-image: docker://ajoergensen/baseimage-alpine:latest
          derived-image: docker://saltiresoul/archive-dovecot:latest

      - name: check for any update
        run: echo "${{steps.check.outputs.differs}}"

  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        #run: echo '${{ toJSON(github) }}'

  build-docker-images:
    needs: check
    name: Build Docker Images
    runs-on: ubuntu-latest
    if: needs.check.outputs.differs == 'true'
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
          
      - id: lowercase-repo-name
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
        
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      #https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables=
      #https://github.com/docker/build-push-action
      - name: Build and Push container image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            ${{ steps.lowercase-repo-name.outputs.lowercase }}:latest
            ghcr.io/${{ steps.lowercase-repo-name.outputs.lowercase }}:latest