name: Publish Docker image (Manually)
on:
  workflow_dispatch:

jobs:
  force-build-docker-images:
    name: Force Build Docker Images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
          
      - id: lowercase-repo-name
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
        
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      #https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables=
      #https://github.com/docker/build-push-action
      - name: Build and Push container image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            ${{ steps.lowercase-repo-name.outputs.lowercase }}:latest
            ghcr.io/${{ steps.lowercase-repo-name.outputs.lowercase }}:latest
