name: "Reactivate Repository Cronjob"

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight
    
permissions:
  contents: "write" # required
  
jobs:
  cronjob:
    runs-on: "ubuntu-latest"
    
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3"
        
      - name: "Reactivate Repository"
        uses: "custom-workflows/reactivate@latest"
        with: 
          commit_message: "github-actions: Reactivate repository"
          committer_username: "GitHub Actions [Bot]"
          committer_email: "github-actions[bot]@users.noreply.github.com"
          days_elapsed: 50